return {
  -- Themes
  'morhetz/gruvbox',
  'arcticicestudio/nord-vim',
  'folke/tokyonight.nvim',
  'rebelot/kanagawa.nvim',
  'joshdick/onedark.vim',
  'cocopon/iceberg.vim',
  'dracula/vim',
  'altercation/vim-colors-solarized',
  'NLKNguyen/papercolor-theme',
  'haishanh/night-owl.vim',
  'mhartington/oceanic-next',
  'sainnhe/everforest',
  'sainnhe/gruvbox-material',
  'EdenEast/nightfox.nvim',
  'marko-cerovac/material.nvim',
  'lifepillar/vim-gruvbox8',
  'sainnhe/edge',
  'sainnhe/sonokai',
  'shaunsingh/moonlight.nvim',
  'projekt0n/caret.nvim',
  'catppuccin/nvim',
  'karoliskoncevicius/sacredforest-vim',
  'overcache/NeoSolarized',
  'Mofiqul/adwaita.nvim',
  'projekt0n/github-nvim-theme',
  'ribru17/bamboo.nvim',
  'comfysage/evergarden',
  'junegunn/seoul256.vim',
  'flrnd/candid.vim',
  -- End of themes
}
